import React from "react";
import { Grid } from "@material-ui/core";
import { makeStyles } from "@material-ui/core/styles";
import { Paper } from "@material-ui/core";
import GalleryImages from "./GalleryImages";
import GalleryTitle from "./GalleryTitle";

const useStyles = makeStyles({
  containerStyle: {
    display: "flex",
    flexDirection: "row",
    flexGrow: 1,
    height: "400px",
    justifyContent: "center",
    webkitDisplay: "flex",
    webkitFlexDirection: "row",
    webkitFlexGrow: 1,
    webkitHeight: "400px",
    webkitJustifyContent: "center",
    mozDisplay: "flex",
    mozFlexDirection: "row",
    mozFlexGrow: 1,
    mozHeight: "400px",
    mozJustifyContent: "center",
    msDisplay: "flex",
    msFlexDirection: "row",
    msFlexGrow: 1,
    msHeight: "400px",
    msJustifyContent: "center",
    "@media only screen and (min-width: 320px) and (max-width: 480px)": {
      display: "flex",
      flexDirection: "row",
      height: "400px",
      justifyContent: "center",
      webkitDisplay: "flex",
      webkitFlexDirection: "row",
      webkitHeight: "400px",
      webkitJustifyContent: "center",
      mozDisplay: "flex",
      mozFlexDirection: "row",
      mozHeight: "400px",
      mozJustifyContent: "center",
      msDisplay: "flex",
      msFlexDirection: "row",
      msHeight: "400px",
      msJustifyContent: "center",
    },
  },
  galleryPosition: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    flexGrow: 1,
    webkitDisplay: "flex",
    webkitAlignItems: "center",
    webkitJustifyContent: "center",
    webkitFlexDirection: "row",
    webkitFlexGrow: 1,
    mozDisplay: "flex",
    mozAlignItems: "center",
    mozJustifyContent: "center",
    mozFlexDirection: "row",
    mozFlexGrow: 1,
    msDisplay: "flex",
    msAlignItems: "center",
    msJustifyContent: "center",
    msFlexDirection: "row",
    msFlexGrow: 1,
    "@media only screen and (min-width: 320px) and (max-width: 480px)": {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      width: "400px",
      webkitDisplay: "flex",
      webkitAlignItems: "center",
      webkitJustifyContent: "center",
      webkitFlexDirection: "row",
      webkitWidth: "400px",
      mozDisplay: "flex",
      mozAlignItems: "center",
      mozJustifyContent: "center",
      mozFlexDirection: "row",
      mozWidth: "400px",
      msDisplay: "flex",
      msAlignItems: "center",
      msJustifyContent: "center",
      msFlexDirection: "row",
      msWidth: "400px",
    },
    "@media only screen and (min-width: 481px) and (max-width: 768px)": {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      width: "300px",
      webkitDisplay: "flex",
      webkitAlignItems: "center",
      webkitJustifyContent: "center",
      webkitFlexDirection: "row",
      webkitWidth: "300px",
      mozDisplay: "flex",
      mozAlignItems: "center",
      mozJustifyContent: "center",
      mozFlexDirection: "row",
      mozWidth: "300px",
      msDisplay: "flex",
      msAlignItems: "center",
      msJustifyContent: "center",
      msFlexDirection: "row",
      msWidth: "300px",
    },
    "@media only screen and (min-width: 769px) and (max-width: 827px)": {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      width: "400px",
      webkitDisplay: "flex",
      webkitAlignItems: "center",
      webkitJustifyContent: "center",
      webkitFlexDirection: "row",
      webkitWidth: "400px",
      mozDisplay: "flex",
      mozAlignItems: "center",
      mozJustifyContent: "center",
      mozFlexDirection: "row",
      mozWidth: "400px",
      msDisplay: "flex",
      msAlignItems: "center",
      msJustifyContent: "center",
      msFlexDirection: "row",
      msWidth: "400px",
    },
    "@media only screen and (min-width: 828px) and (max-width: 1100px)": {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      width: "500px",
      webkitDisplay: "flex",
      webkitAlignItems: "center",
      webkitJustifyContent: "center",
      webkitFlexDirection: "row",
      webkitWidth: "500px",
      mozDisplay: "flex",
      mozAlignItems: "center",
      mozJustifyContent: "center",
      mozFlexDirection: "row",
      mozWidth: "500px",
      msDisplay: "flex",
      msAlignItems: "center",
      msJustifyContent: "center",
      msFlexDirection: "row",
      msWidth: "500px",
    },
    "@media only screen and (min-width: 1101px) and (max-width: 1300px)": {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      width: "600px",
      webkitDisplay: "flex",
      webkitAlignItems: "center",
      webkitJustifyContent: "center",
      webkitFlexDirection: "row",
      webkitWidth: "600px",
      mozDisplay: "flex",
      mozAlignItems: "center",
      mozJustifyContent: "center",
      mozFlexDirection: "row",
      mozWidth: "600px",
      msDisplay: "flex",
      msAlignItems: "center",
      msJustifyContent: "center",
      msFlexDirection: "row",
      msWidth: "600px",
    },
  },
});

/* Gallery раздел */

const GalleryContainer = () => {
  const classes = useStyles();
  return (
    <Paper className={classes.componentStyle}>
      <GalleryTitle />
      <Grid container spacing={3} className={classes.galleryPosition}>
        <Grid item xs={12} sm={6}>
          <GalleryImages />
        </Grid>
      </Grid>
    </Paper>
  );
};

export default GalleryContainer;
