import React from "react";
import NewsCards from "./NewsCards";
import { Grid } from "@material-ui/core";
import { makeStyles } from "@material-ui/core/styles";
import { Paper } from "@material-ui/core";
import NewsTitle from "./NewsTitle";

const useStyles = makeStyles({
  componentStyle: {
    display: "flex",
    flexGrow: 1,
    height: "400px",
    alignItems: "center",
    flexDirection: "column",
    backgroundColor: "#e9e9e9",
    webkitDisplay: "flex",
    webkitFlexGrow: 1,
    webkitHeight: "400px",
    webkitAlignItems: "center",
    webkitFlexDirection: "column",
    webkitBackgroundColor: "#e9e9e9",
    mozDisplay: "flex",
    mozFlexGrow: 1,
    mozHeight: "400px",
    mozAlignItems: "center",
    mozFlexDirection: "column",
    mozBackgroundColor: "#e9e9e9",
    msDisplay: "flex",
    msFlexGrow: 1,
    msHeight: "400px",
    msAlignItems: "center",
    msFlexDirection: "column",
    msBackgroundColor: "#e9e9e9",
    "@media only screen and (min-width: 320px) and (max-width: 480px)": {
      display: "flex",
      height: "800px",
      alignItems: "center",
      flexDirection: "column",
      backgroundColor: "#e9e9e9",
      minWidth: "320px",
      maxWidth: "480px",
      webkitDisplay: "flex",
      webkitHeight: "800px",
      webkitAlignItems: "center",
      webkitFlexDirection: "column",
      webkitBackgroundColor: "#e9e9e9",
      webkitMinWidth: "320px",
      webkitMaxWidth: "480px",
      mozDisplay: "flex",
      mozHeight: "800px",
      mozAlignItems: "center",
      mozFlexDirection: "column",
      mozBackgroundColor: "#e9e9e9",
      mozMinWidth: "320px",
      mozMaxWidth: "480px",
      msDisplay: "flex",
      msHeight: "800px",
      msAlignItems: "center",
      msFlexDirection: "column",
      msBackgroundColor: "#e9e9e9",
      msMinWidth: "320px",
      msMaxWidth: "480px",
    },
    "@media only screen and (min-width: 481px) and (max-width: 768px)": {
      display: "flex",
      height: "800px",
      alignItems: "center",
      flexDirection: "column",
      backgroundColor: "#e9e9e9",
      minWidth: "481px",
      maxWidth: "768px",
      webkitDisplay: "flex",
      webkitHeight: "800px",
      webkitAlignItems: "center",
      webkitFlexDirection: "column",
      webkitBackgroundColor: "#e9e9e9",
      webkitMinWidth: "481px",
      webkitMaxWidth: "768px",
      mozDisplay: "flex",
      mozHeight: "800px",
      mozAlignItems: "center",
      mozFlexDirection: "column",
      mozBackgroundColor: "#e9e9e9",
      mozMinWidth: "481px",
      mozMaxWidth: "768px",
      msDisplay: "flex",
      msHeight: "800px",
      msAlignItems: "center",
      msFlexDirection: "column",
      msBackgroundColor: "#e9e9e9",
      msMinWidth: "481px",
      msMaxWidth: "768px",
    },
  },
  cardStyle: {
    display: "flex",
    flexDirection: "row",
    webkitDisplay: "flex",
    webkitFlexDirection: "row",
    mozDisplay: "flex",
    mozFlexDirection: "row",
    msDisplay: "flex",
    msFlexDirection: "row",
  },
  gridContainerStyle: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    flexGrow: 1,
    webkitDisplay: "flex",
    webkitFlexDirection: "row",
    webkitJustifyContent: "center",
    webkitFlexGrow: 1,
    mozDisplay: "flex",
    mozFlexDirection: "row",
    mozJustifyContent: "center",
    mozFlexGrow: 1,
    msDisplay: "flex",
    msFlexDirection: "row",
    msJustifyContent: "center",
    msFlexGrow: 1,
    "@media only screen and (min-width: 320px) and (max-width: 480px)": {
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      webkitDisplay: "flex",
      webkitFlexDirection: "column",
      webkitJustifyContent: "center",
      mozDisplay: "flex",
      mozFlexDirection: "column",
      mozJustifyContent: "center",
      msDisplay: "flex",
      msFlexDirection: "column",
      msJustifyContent: "center",
    },
    "@media only screen and (min-width: 481px) and (max-width: 768px)": {
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      webkitDisplay: "flex",
      webkitFlexDirection: "column",
      webkitJustifyContent: "center",
      mozDisplay: "flex",
      mozFlexDirection: "column",
      mozJustifyContent: "center",
      msDisplay: "flex",
      msFlexDirection: "column",
      msJustifyContent: "center",
    },
  },
  gridItemStyle: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    flexGrow: 1,
    webkitDisplay: "flex",
    webkitFlexDirection: "row",
    webkitJustifyContent: "center",
    webkitFlexGrow: 1,
    mozDisplay: "flex",
    mozFlexDirection: "row",
    mozJustifyContent: "center",
    mozFlexGrow: 1,
    msDisplay: "flex",
    msFlexDirection: "row",
    msJustifyContent: "center",
    msFlexGrow: 1,
    "@media only screen and (min-width: 320px) and (max-width: 480px)": {
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      webkitDisplay: "flex",
      webkitFlexDirection: "column",
      webkitJustifyContent: "center",
      mozDisplay: "flex",
      mozFlexDirection: "column",
      mozJustifyContent: "center",
      msDisplay: "flex",
      msFlexDirection: "column",
      msJustifyContent: "center",
    },
    "@media only screen and (min-width: 481px) and (max-width: 768px)": {
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      webkitDisplay: "flex",
      webkitFlexDirection: "column",
      webkitJustifyContent: "center",
      mozDisplay: "flex",
      mozFlexDirection: "column",
      mozJustifyContent: "center",
      msDisplay: "flex",
      msFlexDirection: "column",
      msJustifyContent: "center",
    },
  },
});

/* News Раздел */

const NewsContainer = () => {
  const classes = useStyles();
  return (
    <Grid container>
      <Grid item xs={12}>
        <Paper className={classes.componentStyle}>
          <NewsTitle />
          <Grid container className={classes.gridContainerStyle}>
            <Grid item xs={12} sm={12} md={4} className={classes.gridItemStyle}>
              <NewsCards />
            </Grid>
          </Grid>
        </Paper>
      </Grid>
    </Grid>
  );
};

export default NewsContainer;
